scss:
  enabled: false

stylelint:
  enabled: true

ruby:
  config_file: .rubocop.yml

jshint:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc.js
  ignore_file: .eslintignore

fail_on_violations: true
